/**
 * Your albums.
 *
 * 1. Make a subfolder inside /media for each album (optional, but
 *    keeps things tidy) and put the photo/video files in it.
 * 2. Add an entry below for each album: a title, and the list of
 *    files that belong to it.
 * 3. Save this file and refresh index.html in your browser.
 *
 * Supported files: .jpg .jpeg .png .gif .webp .avif   (images)
 *                   .mp4 .webm .mov .m4v .ogv          (video)
 *
 * "cover" is optional — the thumbnail shown on the album shelf.
 * If you leave it out, the first item in the album is used.
 *
 * Give an item a caption by using an object instead of a plain
 * string, e.g. { file: "media/kep/boat.mp4", caption: "Boat ride" }
 */

const ALBUMS = [
  {
    title: "Has Kunthea",
    cover: "Has Kunthea/one.jpg",
    items: [
      "Has Kunthea/one.jpg",
      "Has Kunthea/two.jpg",
      "Has Kunthea/three.jpg",
      "Has Kunthea/four.jpg",
      "Has Kunthea/five.jpg",
      "Has Kunthea/six.jpg",
      "Has Kunthea/seven.jpg",
      "Has Kunthea/eight.jpg",
      "Has Kunthea/nine.jpg",
      "Has Kunthea/ten.jpg",
      "Has Kunthea/eleven.jpg",
      "Has Kunthea/twelve.jpg",
      "Has Kunthea/thirdteen.jpg",
      "Has Kunthea/fourthteen.jpg",
      "Has Kunthea/fifteen.jpg",
      "Has Kunthea/sixteen.jpg",
      "Has Kunthea/seventeen.jpg",
      "Has Kunthea/eighteen.jpg",
      "Has Kunthea/nineteen.jpg",
      "Has Kunthea/twenty.jpg",
      "Has Kunthea/twentyone.jpg",
      "Has Kunthea/twentytwo.jpg",
      "Has Kunthea/twentythree.jpg",
      "Has Kunthea/twentyfour.jpg",
      "Has Kunthea/twentyfive.jpg",
      "Has Kunthea/twentysix.jpg",
      "Has Kunthea/twentyeight.jpg",
      "Has Kunthea/twentynine.jpg",
      "Has Kunthea/thirdty.jpg",
      "Has Kunthea/thirdtyone.jpg",
      "Has Kunthea/thirdtythree.jpg",
      "Has Kunthea/thirdtyfour.jpg",
      "Has Kunthea/thirdtyfive.jpg",
      "Has Kunthea/thirdtysix.jpg",
      "Has Kunthea/thirdtyseven.jpg",
      "Has Kunthea/thirdtyeight.jpg",
      "Has Kunthea/thirdtynine.jpg",
      "Has Kunthea/fourty.jpg",
      "Has Kunthea/fourtyone.jpg",
      "Has Kunthea/fourtytwo.jpg",
      "Has Kunthea/fourtythree.jpg",
      "Has Kunthea/fourtyfour.jpg",
      "Has Kunthea/fourtyfive.jpg",
      "Has Kunthea/fourtysix.jpg",
      "Has Kunthea/fourtyseven.jpg",
      "Has Kunthea/fourtyeight.jpg",
      "Has Kunthea/fourtynine.jpg",
      "Has Kunthea/fifty.jpg",
      "Has Kunthea/fiftyone.jpg",
      "Has Kunthea/fiftytwo.jpg",
      "Has Kunthea/fiftythree.jpg",
      "Has Kunthea/fiftyfour.jpg",
      "Has Kunthea/fiftyfive.jpg",
      "Has Kunthea/fiftysix.jpg",
      "Has Kunthea/fiftyseven.jpg",
      "Has Kunthea/fiftyeight.jpg",
      "Has Kunthea/fiftynine.jpg",
      "Has Kunthea/sixty.jpg",
      "Has Kunthea/sixtyone.jpg",
      "Has Kunthea/sixtytwo.jpg",
      "Has Kunthea/sixtythree.jpg",
      "Has Kunthea/sixtyfour.jpg",
      "Has Kunthea/sixtyfive.jpg",
      "Has Kunthea/sixtysix.jpg",
      "Has Kunthea/sixtyseven.jpg",
      "Has Kunthea/sixtyeight.jpg",
      "Has Kunthea/sixtynine.jpg",
      "Has Kunthea/seventy.jpg",
      "Has Kunthea/seventyone.jpg",
      "Has Kunthea/seventytwo.jpg",
      "Has Kunthea/seventythree.jpg",
      "Has Kunthea/seventyfour.jpg",
      "Has Kunthea/seventyfive.jpg",
      "Has Kunthea/seventysix.jpg",
      "Has Kunthea/seventyseven.jpg",
      "Has Kunthea/seventyeight.jpg",
      "Has Kunthea/seventynine.jpg",
      "Has Kunthea/eighty.jpg",
      "Has Kunthea/eightyone.jpg",
      "Has Kunthea/eightytwo.jpg",
      "Has Kunthea/eightythree.jpg",
      "Has Kunthea/eightyfour.jpg",
      "Has Kunthea/eightyfive.jpg",
      "Has Kunthea/eightysix.jpg",
      "Has Kunthea/eightyseven.jpg",
      "Has Kunthea/eightyeight.jpg",
      "Has Kunthea/eightynine.jpg",
      "Has Kunthea/ninety.jpg",
      "Has Kunthea/ninetyone.jpg",
      "Has Kunthea/ninetytwo.jpg",
      "Has Kunthea/ninetythree.jpg",
      "Has Kunthea/ninetyfour.jpg",
      "Has Kunthea/ninetyfive.jpg",
      "Has Kunthea/ninetysix.jpg",
      "Has Kunthea/ninetyseven.jpg",
      "Has Kunthea/ninetyeight.jpg",
      "Has Kunthea/ninetynine.jpg",
      "Has Kunthea/onehundred.jpg",
    ],
  },

  {
    title : "Heang Seangleng",
    cover : "Heang Seangleng/one.jpg",
    items: [
      "Heang Seangleng/one.jpg",
      "Heang Seangleng/two.jpg",
      "Heang Seangleng/three.jpg",
      "Heang Seangleng/four.jpg",
      "Heang Seangleng/five.jpg",
      "Heang Seangleng/six.jpg",
      "Heang Seangleng/seven.jpg",
      "Heang Seangleng/eight.jpg",
      "Heang Seangleng/nine.jpg",
      "Heang Seangleng/ten.jpg",
      "Heang Seangleng/eleven.jpg",
      "Heang Seangleng/twelve.jpg",
      "Heang Seangleng/thirdteen.jpg",
      "Heang Seangleng/fourteen.jpg",
      "Heang Seangleng/fifteen.jpg",
      "Heang Seangleng/sixteen.jpg",
      "Heang Seangleng/seventeen.jpg",
      "Heang Seangleng/eighteen.jpg",
      "Heang Seangleng/nineteen.jpg",
      "Heang Seangleng/twenty.jpg",
      "Heang Seangleng/twentyone.jpg",
      "Heang Seangleng/twentytwo.jpg",
      "Heang Seangleng/twentythree.jpg",
      "Heang Seangleng/twentyfour.jpg",
      "Heang Seangleng/twentyfive.jpg",
      "Heang Seangleng/twentysix.jpg",
      "Heang Seangleng/twentyseven.jpg",
      "Heang Seangleng/twentyeight.jpg",
      "Heang Seangleng/twentynine.jpg",
      "Heang Seangleng/thirdty.jpg",
      "Heang Seangleng/thirdtyone.jpg",
      "Heang Seangleng/thirdtytwo.jpg",
      "Heang Seangleng/thirdtythree.jpg",
      "Heang Seangleng/thirdtyfour.jpg",
      "Heang Seangleng/thirdtyfive.jpg",
      "Heang Seangleng/thirdtysix.jpg",
      "Heang Seangleng/thirdtyseven.jpg",
      "Heang Seangleng/thirdtyeight.jpg",
      "Heang Seangleng/thirdtynine.jpg",
      "Heang Seangleng/fourty.jpg",
      "Heang Seangleng/fourtyone.jpg",
      "Heang Seangleng/fourtytwo.jpg",
      "Heang Seangleng/fourtythree.jpg",
      "Heang Seangleng/fourtyfour.jpg",
      "Heang Seangleng/fourtyfive.jpg",
      "Heang Seangleng/fourtysix.jpg",
      "Heang Seangleng/fourtyseven.jpg",
      "Heang Seangleng/fourtyeight.jpg",
      "Heang Seangleng/fourtynine.jpg",
      "Heang Seangleng/fifty.jpg",

      "Heang Seangleng/one.MP4", 
      "Heang Seangleng/two.MP4", 
      "Heang Seangleng/three.MP4",
    ],
  },
  {
    title : "Lim Sivphang",
    cover : "Lim Sivphang/twenty.jpg",
    items : [
      "Lim Sivphang/one.jpg",
      "Lim Sivphang/two.jpg",
      "Lim Sivphang/three.jpg",
      "Lim Sivphang/four.jpg",
      "Lim Sivphang/five.jpg",
      "Lim Sivphang/six.jpg",
      "Lim Sivphang/seven.jpg",
      "Lim Sivphang/eight.jpg",
      "Lim Sivphang/nine.jpg",
      "Lim Sivphang/ten.jpg",
      "Lim Sivphang/eleven.jpg",
      "Lim Sivphang/twelve.jpg",
      "Lim Sivphang/thirdteen.jpg",
      "Lim Sivphang/fourteen.jpg",
      "Lim Sivphang/fifteen.jpg",
      "Lim Sivphang/sixteen.jpg",
      "Lim Sivphang/seventeen.jpg",
      "Lim Sivphang/eighteen.jpg",
      "Lim Sivphang/nineteen.jpg",
      "Lim Sivphang/twenty.jpg",
      "Lim Sivphang/twentyone.jpg",
      "Lim Sivphang/twentytwo.jpg",
      "Lim Sivphang/twentythree.jpg",
      "Lim Sivphang/twentyfour.jpg",
      "Lim Sivphang/twentyfive.jpg",
      "Lim Sivphang/twentysix.jpg",
      "Lim Sivphang/twentyseven.jpg",
      "Lim Sivphang/twentyeight.jpg",
      "Lim Sivphang/twentynine.jpg",
      "Lim Sivphang/thirdty.jpg",
      "Lim Sivphang/thirdtyone.jpg",
      "Lim Sivphang/thirdtytwo.jpg",
      "Lim Sivphang/thirdtythree.jpg",
      "Lim Sivphang/thirdtyfour.jpg",
      "Lim Sivphang/thirdtyfive.jpg",
      "Lim Sivphang/thirdtysix.jpg",
      "Lim Sivphang/thirdtyseven.jpg",
      "Lim Sivphang/thirdtyeight.jpg",
      "Lim Sivphang/thirdtynine.jpg",
      "Lim Sivphang/fourty.jpg",
      "Lim Sivphang/fourtyone.jpg",
      "Lim Sivphang/fourtytwo.jpg",
      "Lim Sivphang/fourtythree.jpg",
      "Lim Sivphang/fourtyfour.jpg",
      "Lim Sivphang/fourtyfive.jpg",
      "Lim Sivphang/fourtysix.jpg",
      "Lim Sivphang/fourtyseven.jpg",
      "Lim Sivphang/fourtyeight.jpg",
      "Lim Sivphang/fourtynine.jpg",
      "Lim Sivphang/fifty.jpg",
      "Lim Sivphang/fiftyone.jpg",
      "Lim Sivphang/fiftytwo.jpg",
      "Lim Sivphang/fiftythree.jpg",
      "Lim Sivphang/fiftyfour.jpg",
      "Lim Sivphang/fiftyfive.jpg",
      "Lim Sivphang/fiftysix.jpg",
      "Lim Sivphang/fiftyseven.jpg",
      "Lim Sivphang/fiftyeight.jpg",
      "Lim Sivphang/fiftynine.jpg",
      "Lim Sivphang/sixty.jpg",
      "Lim Sivphang/sixtyone.jpg",
      "Lim Sivphang/sixtytwo.jpg",
      "Lim Sivphang/sixtythree.jpg",
      "Lim Sivphang/sixtyfour.jpg",
      "Lim Sivphang/sixtyfive.jpg",
      "Lim Sivphang/sixtysix.jpg",
      "Lim Sivphang/sixtyseven.jpg",
      "Lim Sivphang/sixtyeight.jpg",
      "Lim Sivphang/sixtynine.jpg",
      "Lim Sivphang/seventy.jpg",
      
      "Lim Sivphang/one.MOV",
    ],
  },

  {
    title : "Pheng Sivchhing",
    cover : "Pheng Sivchhing/one.jpg",
    items : [
      "Pheng Sivchhing/one.jpg",
      "Pheng Sivchhing/two.jpg",
      "Pheng Sivchhing/three.jpg",
      "Pheng Sivchhing/four.jpg",
      "Pheng Sivchhing/five.jpg",
      "Pheng Sivchhing/six.jpg",
      "Pheng Sivchhing/seven.jpg",
      "Pheng Sivchhing/eight.jpg",
      "Pheng Sivchhing/nine.jpg",
      "Pheng Sivchhing/ten.jpg",
      "Pheng Sivchhing/eleven.jpg",
      "Pheng Sivchhing/twelve.jpg",
      "Pheng Sivchhing/thirdteen.jpg",
      "Pheng Sivchhing/fourteen.jpg",
      "Pheng Sivchhing/fifteen.jpg",
      "Pheng Sivchhing/sixteen.jpg",
      "Pheng Sivchhing/seventeen.jpg",
      "Pheng Sivchhing/eighteen.jpg",
      "Pheng Sivchhing/nineteen.jpg",
      "Pheng Sivchhing/one.MP4", 
      "Pheng Sivchhing/two.MP4", 
    ],
  },

  {
    title : "Random Video",
    cover : "Vey Vimean/five.mp4",
    items : [
      "Vey Vimean/one.mov", 
      "Vey Vimean/two.mov", 
      "Vey Vimean/three.mp4",
      "Vey Vimean/four.mp4",
      "Vey Vimean/five.mp4", 
    ],
  },
  // Add more albums below, e.g:
  // {
  //   title: "Kep Weekend",
  //   items: [
  //     "media/kep/sunset.jpg",
  //     "media/kep/boat.mp4",
  //   ],
  // },
];
